# Built with Jekyll 3.2.0

# Setup
title:               El corrido mexicano
tagline:             Encoded text and music for analysis, display, and playback
description:         A demonstration repository of corridos encoded in MEI and plain text that can be searched, displayed, and played in the browser.
url:                 #
baseurl:             '/corridosEd'

# About/contact
author:
  name:              Mark Saccomano
  url:               https://mss2221.github.io/saccomano/
  email:             mark.saccomano@columbia.edu

# Permalinks

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme:

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: "ed."
